# Generated by Django 4.1.4 on 2023-03-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qrcode',
            new_name='Qrcode_gcash',
        ),
    ]
