# Generated by Django 4.1.4 on 2023-03-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_qrcode_qrcode_gcash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode_gcash',
            name='Qr_Code_name',
        ),
    ]
