# Generated by Django 4.1.4 on 2023-03-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_qrcode_gcash_qr_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode_gcash',
            name='Qr_Code_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
