# Generated by Django 4.1.4 on 2023-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_qrcode_gcash_qr_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode_paymaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qr_Code_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
